# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0002_auto_20160427_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='completedstep',
            name='step',
        ),
        migrations.RemoveField(
            model_name='completedstep',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompletedStep',
        ),
    ]
