# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20160427_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='id',
        ),
        migrations.AlterField(
            model_name='step',
            name='step_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
