# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_auto_20160427_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StepData',
            new_name='UserStep',
        ),
    ]
